apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-in-k8
  namespace: default
  labels:
    app: microservices-in-k8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservices-in-k8
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: microservices-in-k8
    spec:
      containers:
      - name: microservices-in-k8
        image: nehashivhare/deployink8
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: microservices-in-k8
spec:
  type: LoadBalancer
  selector:
    app: microservices-in-k8
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
    protocol: TCP
